language: node_js
node_js:
- '10'
repo_token: "$COVERALLS_TOKEN"
before_install:
- curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.13.0
- export PATH=$HOME/.yarn/bin:$PATH
- sudo mysql -e "use mysql; update user set authentication_string=PASSWORD('test') where User='root'; update user set plugin='mysql_native_password';FLUSH PRIVILEGES;"
- sudo mysql_upgrade -u root -ptest
- sudo service mysql restart
- mysql -u root -ptest -e 'create database test character set utf8 collate utf8_general_ci;'
- mysql -u root -ptest test < assets/init.sql

cache: false
git:
  depth: 5
services:
  - mysql
script:
- yarn lint
- yarn test
after_success:
- yarn ci:coverage
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/e4cbb72a5a86450bd6f5
    on_success: change
    on_failure: always
    on_start: never   
addons:
  apt:
    sources:
      - mysql-5.7-trusty
    packages:
      - mysql-server
      - mysql-client